Error: missing script: run-demo
Small fix: 

When I run this: `npm run run-demo` it says `missing script: run-demo` , because it should be `npm run run-demos`